INSERT INTO pessoa (DATA_DE_NASCIMENTO, NOME) VALUES ('1997-05-11', 'Ramon Nascimento Vanderlei');
INSERT INTO pessoa (DATA_DE_NASCIMENTO, NOME) VALUES ('1987-02-15', 'João Silva');
INSERT INTO pessoa (DATA_DE_NASCIMENTO, NOME) VALUES ('1992-09-25', 'Maria Souza');
INSERT INTO pessoa (DATA_DE_NASCIMENTO, NOME) VALUES ('1990-12-03', 'Paulo Santos');
INSERT INTO pessoa (DATA_DE_NASCIMENTO, NOME) VALUES ('1998-04-22', 'Ana Oliveira');


INSERT INTO endereco (ID, CEP, CIDADE, ENDERECO_PRINCIPAL, LOGRADOURO, NUMERO, PESSOA_ID) VALUES ('1','28925-732','Cabo Frio','TRUE','Rua Madre teresa de calcuta','122','1');
INSERT INTO endereco (ID, CEP, CIDADE, ENDERECO_PRINCIPAL, LOGRADOURO, NUMERO, PESSOA_ID) VALUES ('2','28909-490','Cabo Frio','TRUE','Avenida Joaquim Nogueira','98','2');
INSERT INTO endereco (ID, CEP, CIDADE, ENDERECO_PRINCIPAL, LOGRADOURO, NUMERO, PESSOA_ID) VALUES ('3','28907-410','Cabo Frio','TRUE','Avenida Teixeira e Souza - até 1261 - lado ímpar','77','3');
INSERT INTO endereco (ID, CEP, CIDADE, ENDERECO_PRINCIPAL, LOGRADOURO, NUMERO, PESSOA_ID) VALUES ('4','28922-030','Cabo Frio','TRUE','Rua Jorge Veiga','122','4');
INSERT INTO endereco (ID, CEP, CIDADE, ENDERECO_PRINCIPAL, LOGRADOURO, NUMERO, PESSOA_ID) VALUES ('5','28905-020','Cabo Frio','TRUE','Rua José Paes de Abreu','122','5');
INSERT INTO endereco (ID, CEP, CIDADE, ENDERECO_PRINCIPAL, LOGRADOURO, NUMERO, PESSOA_ID) VALUES ('6','29025-777','Aquariús','FALSE','Rua Doze','122','1');